require("packer_plugins")
require("colorscheme")
require("keymappings")
require("settings")

require("umbe.telescope")
require("umbe.treesitter")
require("umbe.indent")
require("umbe.lualine")
require("umbe.orgmode")
require("umbe.comment")
require("umbe.lightbulb")
require("umbe.completion")
require("umbe.git")
require("umbe.mason")
require("umbe.lsp")
require("umbe.nvim-tree")

--Personal Plugins
require("gitignore").setup()
