#!/usr/bin/env bash

TMUX_WORKSPACE_FILE=".workspace.tmux"

PROJECT_FOLDER=$1
if ! [ -n "$PROJECT_FOLDER" ]; then
	if [ -n "$DEFAULT_PROJECT_LOCATION" ]; then
	    PROJECT_FOLDER="$DEFAULT_PROJECT_LOCATION"
	else
		PROJECT_FOLDER="."
	fi
fi

cd "$PROJECT_FOLDER"
selected_folder=$(/usr/bin/ls -1 . | fzf --reverse)

if ! [ -n "$selected_folder" ]; then
	exit 0
fi

cd "$selected_folder"
SESSION_EXISTS=$(tmux list-sessions -F "#{session_name}" | rg "$selected_folder")

if [ -z "$SESSION_EXISTS" ]; then
    tmux new -d -s "$selected_folder"
    if [ -f "$TMUX_WORKSPACE_FILE" ]; then
        source "$TMUX_WORKSPACE_FILE"
    fi
fi
ta "$selected_folder"
