#!/usr/bin/env bash

PROJECT_FOLDER=$1
if ! [ -n "$PROJECT_FOLDER" ]; then
	if [ -n "$DEFAULT_PROJECT_LOCATION" ]; then
	    PROJECT_FOLDER="$DEFAULT_PROJECT_LOCATION"
	else
		PROJECT_FOLDER="."
	fi
fi

cd "$PROJECT_FOLDER"
selected_folder=$(/usr/bin/ls -1 . | fzf --reverse)

if ! [ -n "$selected_folder" ]; then
	exit 0
fi

cd "$selected_folder"
tmux new -d -s "$selected_folder"
ta "$selected_folder"
