#!/usr/bin/env bash

# speedtest --server-id=$(speedtest --servers | tail -n +5 | fzf --reverse | awk '{print $1}')
speedtest --server $(speedtest --list | tail -n +2 | fzf --reverse | awk '{print $1+0}')
echo ""
echo ""
echo "Press any key to close..."
read -r foo
