#!/usr/bin/env bash
if ! [ -n "$1" ]; then
	SESSION_NAME=$(tmux ls -F '#{session_name}' | fzf --reverse)
else
	SESSION_NAME=$1
fi

if ! [ -n "$SESSION_NAME" ]; then
    #No session selected
    exit 0
fi

if ! [ -n "$TMUX" ]; then
    #if not tmux session attach to selected
    tmux attach -t $SESSION_NAME
else
    #if in a session detach current session and then attach te selected one
    tmux switch -t $SESSION_NAME
    tmux display-message -d 1000 "    #[bold]Switched#[default] to session #[bold]$SESSION_NAME"
fi
