#!/usr/bin/env bash
SESSION_NAME=$(tmux ls -F '#{session_name}' | fzf --reverse)
if ! [ -n "$TMUX" ]; then
    #if not tmux session attach to selected
    tmux attach -t $SESSION_NAME
else
    #if in a session detach current session and then attach te selected one
    tmux switch -t $SESSION_NAME
    tmux display-message "Switched to session $SESSION_NAME"
fi
