#!/usr/bin/env bash

DESTINATION=$1
if [ -z "$DESTINATION" ]; then
	DESTINATION="."
fi

cp "$HOME/.scripts/default_workspace.tmux" "$DESTINATION/.workspace.tmux"
chmod +x "$DESTINATION/.workspace.tmux"
