#!/usr/bin/env bash
if ! [ -n "$1" ]; then
	SESSION_NAME=$(tmux ls -F '#{session_name}' | fzf --reverse)
else
	SESSION_NAME=$1
fi

if [ -n "$SESSION_NAME" ]; then
    tmux kill-session -t "$SESSION_NAME"
fi
