#!/usr/bin/env bash

SESSION_NAME=$(tmux ls -F '#{session_name}' | rg notes)
if [ -z "$SESSION_NAME" ]; then
    SESSION_NAME="notes"
    cd "$HOME/my-orgs"
    tmux new -d -s "$SESSION_NAME"
    echo "$SESSION_NAME:1"
    tmux renamew -t "$SESSION_NAME:1" "Notes"
    tmux send -t "$SESSION_NAME:1" "nvim ." C-m
fi

tmux attach -t $SESSION_NAME
# source .tmux.conf
