#!/usr/bin/env bash

#Create working session
tmux new -d -s "works" -c "$HOME"
tmux neww -t "works:" -c "$HOME"
tmux selectw -t "works:1"

#Create notes session
tmux new -d -s "notes" -c "$HOME/my-orgs"
tmux send -t "notes:" "nvim ." C-m 

tmux attach -t "works"
